# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-17 09:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('description', models.TextField()),
                ('unit_measure', models.CharField(max_length=100)),
                ('no_of_units', models.IntegerField(default=100)),
                ('period_of_measure', models.CharField(max_length=100)),
            ],
        ),
    ]
