# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-17 15:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventorylist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
